exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

title: monka.tv
url: "https://barnie995.github.io/monka.tv"

remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

collections_dir: streamers
collections:
  fl0m:
    output: true
    permalink: /:collection/:slug